language: node_js
node_js:
  - "6.9.4"
script: npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "spa2017"
  region: 'eu-central-1'
  local_dir: public
  skip_cleanup: true
